### ISSUE TITLE
Add flutter animation in the main.dart

### ISSUE THREAD

**Issue by SuvamPrasd** [SuvamPrasd/WeAdoreYou#1]
### Flutter Animation
Before proceeding to this issue. **Make sure, do not use an external flutter package for adding the animation**. Try to implement minimal animation. This app will be uploaded to the Play Store.

- [ ] Incase you want to add an external animation package, first tell me.
- [ ] We need minimal animation.

**Comment by shathurshan** [comment]
I am interested

**Comment by SuvamPrasd** [comment]
Have you worked on any flutter project before?

**Comment by shathurshan** [comment]
> Have you worked on any flutter project before?

Yes

**Comment by SuvamPrasd** [comment]
Great. Start your coding.
